import { AlertCircle, Database, ChevronLeft, ChevronRight, Search } from 'lucide-react';
import { Json, statuses } from './api';
export function Badge({status}:{status:string}){return <span className={`badge state-${status}`} title={status}><i/>{statuses[status]||status}</span>}
export function Empty({title='暂无记录',text='连接实际运行账本后，相关记录会显示在这里。'}:{title?:string;text?:string}){return <div className="empty"><Database size={30} strokeWidth={1.2}/><h3>{title}</h3><p>{text}</p></div>}
export function Notice({error,loading=false}:{error?:string;loading?:boolean}){return error?<div className="notice" role="alert"><AlertCircle size={16}/><span>{error}。已显示的数据可能过期。</span></div>:loading?<div className="loading" role="status">正在读取实际账本…</div>:null}
export function Raw({value,label='原始记录'}:{value:unknown;label?:string}){return <details className="raw"><summary>{label}</summary><pre>{JSON.stringify(value,null,2)}</pre></details>}
export function Field({label,children}:{label:string;children:React.ReactNode}){return <div className="field"><span>{label}</span><div>{children??'未记录'}</div></div>}
export function Pager({offset,total,limit,onChange}:{offset:number;total:number;limit:number;onChange:(offset:number)=>void}){return <div className="pager"><span>{total?`${offset+1}–${Math.min(offset+limit,total)} / ${total} 条`:'0 条记录'}</span><button className="icon-button" disabled={offset===0} onClick={()=>onChange(Math.max(0,offset-limit))} aria-label="上一页"><ChevronLeft size={16}/></button><button className="icon-button" disabled={offset+limit>=total} onClick={()=>onChange(offset+limit)} aria-label="下一页"><ChevronRight size={16}/></button></div>}
export function SearchBox({value,onChange,label='搜索记录'}:{value:string;onChange:(text:string)=>void;label?:string}){return <label className="search"><Search size={16}/><input value={value} onChange={e=>onChange(e.target.value)} aria-label={label}/>{!value&&<span aria-hidden>{label}</span>}</label>}
export function Evidence({items,onAsset}:{items?:Json[];onAsset?:(id:string)=>void}){return items?.length?<div className="evidence">{items.map((e,i)=><div key={i}><span className="small-label">证据 {i+1}</span>{typeof e.source==='string'&&e.source.startsWith('asset:')&&onAsset?<button className="text-button mono" onClick={()=>onAsset(e.source.slice(6))}>{e.source}</button>:<code>{String(e.source??'来源缺失')}</code>}{e.sha256&&<span className="hash">SHA256 {e.sha256}</span>}<Raw value={e} label="证据字段"/></div>)}</div>:<p className="muted">未记录来源证据</p>}
